name: Build Mac Executable

on:
  push:
    branches: [ main ]  # main 브랜치에 코드가 올라오면 실행

jobs:
  build:
    runs-on: macos-latest  # 맥 OS 서버에서 실행

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install pyinstaller pandas openpyxl selenium

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --noconsole --collect-all tkinter naver1.0.py

    - name: Upload Result
      uses: actions/upload-artifact@v3
      with:
        name: NaverBot-Mac
        path: dist/naver1.0  # 빌드된 파일 경로
